name: Clear Content Except Workflows
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0' 

jobs:
  clear:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        with: 
          ref: gh-pages 

      - name: Execute cleanup command
        run: |
          ls -d */ | grep -v ".github/" | xargs rm -rf

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clear content"