name: Clear Content
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  clear:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          ref: gh-pages

      - name: Clear content except workflows
        run: |
          find. | grep -v ".github" | xargs rm -rf
          git add.
          git commit -m "Clear content"
          git push